name: Build & Test
on: [pull_request]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set Node.js 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Run install
              uses: borales/actions-yarn@v4
              with:
                  cmd: install

            - name: AutoClean
              run: |
                  yarn autoclean

            - name: Build production bundle
              uses: borales/actions-yarn@v4
              with:
                  cmd: build

            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: production-files
                  path: ./dist

            - name: Lint the app
              uses: borales/actions-yarn@v4
              with:
                  cmd: eslint:all

            - name: Test the app
              uses: borales/actions-yarn@v4
              with:
                  cmd: test
