name: Build & Deploy
on:
    pull_request:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        run: |
            git config --global user.email 'github-actions@github.com'
            git config --global user.name 'github-actions'

        steps:
            - uses: actions/checkout@v3
            - name: Set Node.js 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
            - name: Run install
              uses: borales/actions-yarn@v4
              with:
                  cmd: install # will run `yarn install` command
            - name: Build production bundle
              uses: borales/actions-yarn@v4
              with:
                  cmd: build # will run `yarn build` command

            - name: Deploy production build
              uses: borales/actions-yarn@v4
              with:
                  cmd: deploy
