name: Deployment

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  persist-credentials: false

            - name: Install
              run: yarn install

            - name: Set Node.js 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Run install
              uses: borales/actions-yarn@v4
              with:
                  cmd: install # will run `yarn install` command

            - name: AutoClean
              run: |
                  yarn autoclean

            - name: Build production bundle
              uses: borales/actions-yarn@v4
              with:
                  cmd: build # will run `yarn build:prod` command

            - name: Deploy to GH Page
              uses: JamesIves/github-pages-deploy-action@4.1.1
              with:
                  branch: gh-pages
                  folder: dist
